# Tasks
### - plot all variables that seem to be important for assessing change
### - we seem to have a highly dimensional problem here. 
### - make a categorical variable for change and use this?
### - maps with proportional change per cell??


# Libraries
```{r}
library(dplyr)
library(ggplot2)
library(randomForestSRC)
library(sf)
library(randomForestExplainer)
```

# Data
```{r}
dat <- readRDS("../../out/rds/Final_data.rds")
sf_dat <- readRDS("../../out/rds/presence_sf_list.rds")
names(sf_dat[[1]])
names(dat)
```

# Pre-processing
```{r}
hist(dat$log_R2_1, breaks = 300)
mean(dat$log_R2_1)
median(dat$log_R2_1)
range(dat$log_R2_1)


## Add trend column for plotting:
# Define your factor levels
factor_levels <- c("strong decrease (> halfing)", 
                   "weak decrease (< halfing)", 
                   "stable", 
                   "weak increase (< doubling)", 
                   "strong increase (> doubling)")

# Define the cutoff points for the ranges in log scale
cutoff_points <- c(-Inf, log(0.5), log(0.9), log(1.1), log(2), Inf)
dat2 <- dat

# Convert the log ratios to factor variables based on the ranges
dat2$trend <- cut(dat2$log_R2_1, breaks = cutoff_points, labels = factor_levels) 
dat2 <- dat2 %>% 
  rstatix::reorder_levels(trend, factor_levels)

sf2_list<-list()
for (i in seq_along(sf_dat)){
  sf1 <- sf_dat[[i]]
  sf1$tp <- as.factor(sf1$tp)
    sf2 <- left_join(sf1, dat2 %>% select(-area) %>% filter(dataset == names(sf_dat)[i])) %>%
      group_by(tp, cell_label) %>%
      mutate(mean_trend_cell = mean(log_R2_1, na.rm=T))
    
    sf2_list[[i]] <- sf2
}
```

# Test plot
```{r}
rm(sf_dat, sf2, sf1)

p_list <- list()
for (i in seq_along(sf2_list)){
  
  sf_test <- sf2_list[[i]] %>% select(cell_label, mean_trend_cell, tp)%>% na.omit() %>% unique()
p <-print(ggplot(sf_test) +
  aes(fill = mean_trend_cell) +
  geom_sf(size = 1.2) +
  scale_fill_distiller(palette = "RdYlBu", direction = 1) +
  theme_minimal() +
  facet_wrap(vars(tp)))

p_list[[i]] <- p
  
}

p1 <- p_list[[1]]
p2 <- p_list[[2]]
p3 <- p_list[[3]]
p4 <- p_list[[4]]


sf_test %>%
ggplot()+
  geom_sf(aes(fill = mean_trend_cell))


esquisse::esquisser(sf_test)

```

# Fig 1 & Fig 2
```{r}
# Plot number of species per trend per dataset
fig1 <- dat2 %>% 
    group_by(dataset, trend) %>% 
    summarise(n_sp = n_distinct(verbatim_name)) %>% 
ggplot(aes(y = n_sp, x = trend, fill = trend))+
    geom_col()+
    facet_grid(~dataset)+
    theme_classic()+
    scale_fill_manual(values = c("#d7191c", "#fdae61", "#ffffbf", "#abd9e9", "#2c7bb6" )) +
    labs(title = "Trends ~ Nr of species") + 
  theme(
    axis.line = element_line(colour = "azure4",
    linetype = "solid"), axis.ticks = element_line(colour = "gray13"),
    panel.grid.major = element_line(colour = "gray97"),
    panel.grid.minor = element_line(linetype = "blank"), 
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 10),
    axis.text.x = element_text(angle = 45, vjust = 0.9, hjust = 0.9),
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5, vjust = 2),
    panel.background = element_rect(fill = NA),
    plot.background = element_rect(colour = NA),
    legend.position = "none") +
  labs(x = "Occupancy trend", y = "Number of Species",
    fill = NULL) 

# Plot Log Ratio ~ trend as check
## Overview of Log ratio ~ Trend / Mass just for visualization of the categories
fig2 <- ggplot(dat2) +
  aes(x = trend, y = log_R2_1, colour = trend, size = Mass) +
  geom_jitter(alpha = 0.4) +
  scale_color_manual(
    values = c(`strong decrease` = "#A50026",
    `weak decrease` = "#F88D51",
    stable = "#FFFFBF",
    `weak increase` = "#8FC3DD",
    `strong increase` = "#313695")
  ) +
  labs(
    y = "log ratio AOO",
    color = "Trend",
    size = "Body Mass"
  ) +
  theme_classic() +
  facet_wrap(vars(dataset))+
    theme(
    axis.line = element_line(colour = "azure4",
    linetype = "solid"), axis.ticks = element_line(colour = "gray13"),
    panel.grid.major = element_line(colour = "gray97"),
    panel.grid.minor = element_line(linetype = "blank"), 
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 10),
    axis.text.x = element_text(angle = 45, vjust = 0.9, hjust = 0.9),
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5, vjust = 2),
    panel.background = element_rect(fill = NA),
    plot.background = element_rect(colour = NA))
```

# Classification model
```{r}
discrete_m0 <- randomForestSRC::rfsrc(factor(trend) ~ ., dat2 %>% filter(tp == 1) %>% select(-tp, -verbatim_name, -log_R2_1, -Telfer_1_2))
numeric_m0 <- randomForestSRC::rfsrc(log_R2_1 ~ ., dat2 %>% filter(tp == 1) %>% select(-tp,-verbatim_name, -Telfer_1_2, -trend))
topvars1 <- randomForestSRC::vimp(discrete_m0)
#print(vimp(numeric_m0, importance = "permute", join = T))
plot(discrete_m0)
plot(numeric_m0)
plot(get.tree(discrete_m0, 10, target = "strong decrease", class.type = "bayes", ensemble = TRUE))
plot(get.tree(numeric_m0, 10, ensemble = TRUE))


 dat2 %>% filter(tp == 1) %>% group_by(dataset, trend) %>% summarise(n_sp = n_distinct(verbatim_name),
                                                                     prop_sp = round(n_distinct(verbatim_name)/Gamma, 2)) %>% distinct()

 
# Summary of trends 
dat2 %>% filter(tp == 1) %>% distinct(dataset, verbatim_name, trend, log_R2_1) %>% write.csv("../../Documents/documentation_methods/Trends.csv")


good_sp <- dat2 %>% filter(tp == 1 & trend == "increase") %>% group_by(dataset, tp) %>% summarise(n_sp = n_distinct(verbatim_name))
bad_sp <- dat2 %>% filter(tp == 1 & trend == "decrease")%>% group_by(dataset, tp) %>% summarise(n_sp = n_distinct(verbatim_name))

```


```{r}
 dat2 %>% filter(trend == "increase") %>% group_by(dataset, tp) %>% 
 ggplot(aes(y = log_R2_1, x = D_AOO_a))+
 geom_point()+
 geom_smooth()+
 facet_wrap(~dataset)+
 theme_classic()

dat2 %>% filter(trend == "decrease") %>% group_by(dataset, tp) %>% 
 ggplot(aes(y = log_R2_1, x = D_AOO_a))+
 geom_point()+
 geom_smooth()+
 facet_wrap(~dataset)+
 theme_classic()

dat2 %>% filter(trend == "stable") %>% group_by(dataset, tp) %>% 
 ggplot(aes(y = log_R2_1, x = D_AOO_a))+
 geom_point()+
 geom_smooth()+
 facet_wrap(~dataset)+
 theme_classic()

#####

 dat2 %>% filter(trend == "increase") %>% group_by(dataset, tp) %>% 
 ggplot(aes(y = log_R2_1, x = Mass))+
 geom_point()+
 geom_smooth()+
 facet_wrap(~dataset,  scales = "free")+
 theme_classic()

dat2 %>% filter(trend == "decrease") %>% group_by(dataset, tp) %>% 
 ggplot(aes(y = log_R2_1, x = Mass))+
 geom_point()+
 geom_smooth()+
 facet_wrap(~dataset, scales = "free")+
 theme_classic()

dat2 %>% filter(trend == "stable") %>% group_by(dataset, tp) %>% 
 ggplot(aes(y = log_R2_1, x = Mass))+
 geom_point()+
 geom_smooth()+
 facet_wrap(~dataset, scales = "free")+
 theme_classic()

#####
```