---
title: "Taxonomic Harmonization"
author: "Frieda"
format: html
editor: visual
---

```{r}
library(dplyr)
rm(list=ls())
### The paths =================================================
source_atlas <- c("c:/Users/wolke/OneDrive - CZU v Praze/Datasets/Processed/Atlases/Replicated/")
source_predictors <- c("c:/Users/wolke/OneDrive - CZU v Praze/Dokumenty/PhD_Projects/StaticPredictors/Data/")
source_Git <- c("c:/Users/wolke/OneDrive - CZU v Praze/Dokumenty/GitHub/BEAST_General_Procedures/Project_Frieda/StaticPredictors/")
out_path <- c(paste0(source_Git, "out/"))

# folder path to atlas data
source_paths <- c(
  paste0(source_atlas, "Birds_Atlas_Czechia/"),
  paste0(source_atlas, "Birds_Atlas_New_York/"),
  paste0(source_atlas, "Birds_atlas_Japan/"),
  paste0(source_atlas, "Birds_atlas_EBBA/")
)

# create path to read in data and grids from variables
data_paths <- c(paste0(source_paths[1],"Birds_Atlas_Czechia_data_INFO_spnames.csv"), 
                paste0(source_paths[2], "Birds_Atlas_New_York_spnames_INFO.csv"), 
                paste0(source_paths[3], "Birds_atlas_Japan_spnames_INFO.csv"),
                paste0(source_paths[4], "Birds_atlas_EBBA_spnames_INFO.csv"))
atlas_names <- c("Birds_Atlas_Czechia", "Birds_Atlas_New_York","Birds_atlas_Japan", "Birds_atlas_EBBA")
name_vector <- read.csv("out/csv/sp_names_predictors.csv")[,2] %>% unique() #734 sp

avonet <- read.csv(paste0(source_predictors, "AVONET/ELEData/TraitData/AVONET_Raw_Data.csv"), na.strings = c("#N/A", "<NA>", "NA")) %>%
  rename("sp_BirdLife" = "Species1_BirdLife",
         "sp_eBird" = "Species2_eBird",
         "sp_BirdTree" = "Species3_BirdTree") %>% select(sp_BirdLife, sp_eBird, sp_BirdTree, eBird.species.group)

BirdLifeTax <- read.csv(paste0(out_path, "csv/BOTW_TaxChecklist.csv"))


BirdTreeTax <- read.csv(paste0(source_predictors, "BirdTree_taxonomy.txt")) %>% rename("sp_BirdTree" = "Scientific")
```

```{r}

# Original species names:

dfs <- lapply(data_paths, read.csv)
dfs2 <- plyr::rbind.fill(dfs)
dfs3 <- dfs2 %>% 
  filter(name_in_data %in% name_vector) %>% 
  select(-cellID) %>% 
  distinct(name_in_data, original_verbatim_name, .keep_all = T) %>%
  rename("sp_BirdLife" = "BirdLife",
         "sp_eBird" = "eBird.Clements")
colSums(is.na(dfs3))


dfs3 %>% filter(wordCount != 2)


# AVONET

avonet <- left_join(dfs3, avonet)%>% distinct(name_in_data, .keep_all=T)
colSums(is.na(avonet))

# BIRDLIFE international range maps
TaxLookUp <- avonet %>% left_join(BirdLifeTax %>% rename("sp_BirdLife" = "ScientificName"))
colSums(is.na(TaxLookUp))

# BIRDTREE
intersect(TaxLookUp$name_in_data, BirdTreeTax$sp_BirdTree) %>% length() # 690
setdiff(TaxLookUp$name_in_data, BirdTreeTax$sp_BirdTree) %>% length() # 84

merge(TaxLookUp, BirdTreeTax, by.x=c("name_in_data"), by.y=c("sp_BirdTree")) %>%
  write.csv(paste0(out_path, "csv/TaxLookUp_final_v2.csv"))



```
