---
title: "0_4_Correlations"
author: "Frieda"
format: html
editor: visual
---

## Correlation Analysis - Static Predictors

```{r}
rm(list=ls())

library(dplyr); library(ggplot2);library(ggcorrplot)

df <- readRDS("out/rds/All_predictors.rds")
str(df)
colSums(is.na(df))

df %>% group_by(dataset, tp) %>% 
  summarise(across(everything(), ~ sum(is.na(.x)))) %>% 
  write.csv("out/csv/Summary_NAs_All_predictors.csv")

str(df)
df <- df %>% 
  select(-Family, -Order, -verbatim_name, -sp_atlas.adapted1, -avgEffort)%>% unique() %>%
  mutate(HWI = as.numeric(as.character(HWI)),
         Mass = as.numeric(as.character(Mass)),
         Range.Size = as.numeric(as.character(Range.Size)),
         FP = as.numeric(FP),
         tp = as.integer(tp),
         dataset = as.factor(dataset),
         Habitat = as.factor(Habitat),
         RL_Category = as.factor(RL_Category),
         Habitat.Density = as.factor(Habitat.Density),
         Migration = as.factor(Migration),
         Trophic.Level = as.factor(Trophic.Level),
         Trophic.Niche = as.factor(Trophic.Niche),
         Primary.Lifestyle = as.factor(Primary.Lifestyle),
         grain = as.integer(grain)) %>%
  select(-Total_Ncells_samp, -atlas_bearing, -atlas_bearingMinRect, -atlas_circ, -atlas_elonMinRect, -atlas_widthMinRect, -atlas_lengthMinRect, -atlas_xmin, -atlas_ymin, -atlas_xmax, -atlas_ymax, -atlas_yhalf, -atlas_xhalf, -bearing, -bearingMinRect, -circ, -elonMinRect, -widthMinRect, -lengthMinRect, -increment2)

str(df)

```

```{r}

cor_df <- df
cor_df_num <- cor_df %>% select(where(is.numeric)) %>% na.omit()

# Check correlation in all predictors
p.mat <-  model.matrix(~0+., data=cor_df) %>% ggcorrplot::cor_pmat()
pdf(file="out/figures/Correlation_matrix_all.pdf", paper = "a4")
model.matrix(~0+., data=cor_df) %>% 
  cor(use="pairwise.complete.obs") %>% 
  ggcorrplot(lab=TRUE, 
  method = "square", 
  lab_size=0.8, 
  hc.order=T, 
  insig ="blank",
  #p.mat = p.mat, 
  tl.cex = 5, 
  type = "upper", 
  digits = 1)
dev.off()

# Find highly correlated variables
highCor <- caret::findCorrelation(cor(cor_df_num), cutoff = 0.8, names=T, exact = F) 

# Remove columns 
df2 <- cor_df %>% 
  select(-one_of(highCor)) 


# Check correlation again

p.mat <-  model.matrix(~0+., data=df2%>% select(where(is.numeric))) %>% ggcorrplot::cor_pmat()
pdf(file="out/figures/Correlation_matrix_reduced.pdf", paper = "a4")
model.matrix(~0+., data=df2%>% select(where(is.numeric))) %>% 
  cor(use="pairwise.complete.obs") %>% 
  ggcorrplot(lab=TRUE, 
  method = "square", 
  lab_size=2, 
  hc.order=T, 
  insig ="blank",
  p.mat = p.mat, 
  tl.cex = 10, 
  type = "full", 
  digits = 2)
dev.off()

# save final data
saveRDS(df2, "out/rds/Final_data.rds")

```
