---
title: "Prep_Example_Spec"
author: "Frieda"
format: html
editor: visual
---

## Variables

```{r}
library(dplyr); library(sf)

# source folder
source_Git <- c("c:/Users/wolke/OneDrive - CZU v Praze/Dokumenty/GitHub/BEAST_General_Procedures/Project_Frieda/StaticPredictors/")

# folder path to output folder
out_path <- c(paste0(source_Git, "out/"))

# data
df <- readRDS(paste0(out_path, "rds/All_predictors.rds"))

```

Task:

-   select 10 species that are increasing

-   select 10 species that are decreasing

-   Plot some relations in the data

-   Maps!

```{r}
presence_sf <- readRDS(paste0(out_path, "rds/presence_sf_list.rds"))

ss <- presence_sf[[1]] 

ss %>% filter(verbatim_name == "Ciconia nigra" & tp == 1) %>% plot()
ss %>% filter(verbatim_name == "Ciconia nigra" & tp == 2) %>% plot()


```

## increasing species vs. decreasing sp

```{r}

 df %>% filter(log_R2_1 > 0 & tp == 1) %>% group_by(dataset) %>% distinct(dataset, tp, verbatim_name, .keep_all = T) %>% summarise(N_sp = n_distinct(verbatim_name)) %>% ggplot2::ggplot(aes(x = dataset, y = N_sp))+ geom_col()+ labs(title = "increase")
 
 
 df %>% filter(log_R2_1 < 0 & tp == 1) %>%  group_by(dataset)%>% distinct(dataset, tp, verbatim_name, .keep_all = T) %>% summarise(N_sp = n_distinct(verbatim_name)) %>% ggplot2::ggplot(aes(x = dataset, y = N_sp))+ geom_col() + labs(title = "decrease")


```

```{r}
df %>% filter(verbatim_name == "Ciconia nigra")


```
