---
title: "Taxonstand"
format: html
editor: visual
---

## Libraries & Database

```{r}
rm(list=ls())
# devtools::install_github("ecoinfor/U.Taxonstand")
library(U.Taxonstand)
library(dplyr)
?nameMatch

require(openxlsx)
databaseAves <- read.xlsx("Taxonomic/Birds_ITIS_database.xlsx") 
# formatted ITIS Aves database: https://github.com/nameMatch/Database


```

## Atlas Species

```{r}

sp_dat <- read.csv("out/csv/sp_names_data.csv")
sp_dat <- sp_dat$scientificName


test <- nameMatch(spList = sp_dat, author = F, spSource = databaseAves) 
colSums(is.na(test)) # 10 NA for accepted sp name
test %>% filter(is.na(Accepted_SPNAME))

test <- test %>%  filter(!is.na(Accepted_SPNAME))

```

## Phylogeny Species

```{r}
Birdtree_dat <- read.csv("out/csv/EvolDistinctness.csv") 
Birdtree_dat_v <-  Birdtree_dat %>% pull(sp_BirdTree) 

BT_matched <- nameMatch(spList = Birdtree_dat_v, author = F, spSource = databaseAves)
colSums(is.na(BT_matched)) # 24 NA for accepted sp name

setdiff(test$Submitted_Name, BT_matched$Submitted_Name) # 84 different
setdiff(test$Accepted_SPNAME, BT_matched$Accepted_SPNAME) # 17 species not matched !! only!! 

BT_merged <- merge(Birdtree_dat, BT_matched %>% select(Submitted_Name, Accepted_SPNAME), by.x = "sp_BirdTree", by.y = "Submitted_Name" )

BT_matched %>% filter(Accepted_SPNAME %in% test$Accepted_SPNAME) %>% select(Submitted_Name, Accepted_SPNAME) %>% filter(is.na(Accepted_SPNAME))


```

## BirdLife Ranges species

```{r}

BirdLife_dat <- readRDS("out/rds/RangeSizeBOTW_df.rds") %>% distinct(sci_name) %>% pull(sci_name) 
BL_matched <- nameMatch(spList = BirdLife_dat, author = F, spSource = databaseAves)


BL_merged <- left_join(test %>%
                         distinct(Submitted_Name, Accepted_SPNAME) %>% 
                         rename("sp_atlas" = "Submitted_Name"), 
                       BL_matched %>%
                         distinct(Submitted_Name, Accepted_SPNAME) %>% 
                         rename("sp_sci_name" = "Submitted_Name"))

setdiff(test$Submitted_Name, BL_matched$Submitted_Name) # 102 different
#setdiff(BT_matched$Accepted_SPNAME, BL_matched$Accepted_SPNAME)
setdiff(test$Accepted_SPNAME, BL_matched$Accepted_SPNAME) # 38 species different

write.csv(BL_merged, "Taxonomic/BirdLife_TaxLookup_UTaxonstand.csv")


```

## Avonet species

```{r}
# AVONET data that was reduced to species in data
AVONET_dat <- read.csv2("out/csv/AVONET_final.csv") 
AVONET_dat_v <- AVONET_dat %>% pull(sp_atlas.adapted1) %>% unique()
AVONET_dat_matched <- nameMatch(spList = AVONET_dat_v, author = F, spSource = databaseAves)
AVONET_dat_merged <- merge(AVONET_dat, AVONET_dat_matched, by.x=c("sp_atlas.adapted1"), by.y="Submitted_Name")

# Full AVONET species lists from all different Taxonomies:
Avonet_sp <- read.csv("C:/Users/wolke/OneDrive - CZU v Praze/Dokumenty/PhD_Projects/StaticPredictors/Data/AVONET/ELEData/TraitData/AVONET_Extant_Species_List.csv") 
Avonet_sp_v <- Avonet_sp %>% pull(Species.name)
AVONET_matched <- nameMatch(spList = Avonet_sp_v, author = F, spSource = databaseAves)
# Merge it
Avonet_sp_merged <- merge(Avonet_sp, AVONET_matched, by.x=("Species.name"), by.y=c("Submitted_Name"))

# Checking matches:
setdiff(setdiff(test$Submitted_Name, AVONET_matched$Submitted_Name), #89 not matched.
setdiff(test$Accepted_SPNAME, AVONET_matched$Accepted_SPNAME)) #69 not matched. hm.


## Merging AVONET:
AVONET_full_merged <- left_join(AVONET_dat_merged, Avonet_sp_merged)
AVONET_full_merged[AVONET_full_merged=="#N/A"] <- NA
head(AVONET_full_merged)
colSums(is.na(AVONET_full_merged))

AVONET_FINAL <- AVONET_full_merged %>% 
  distinct(sp_atlas, Accepted_SPNAME, 
           Hand.Wing.Index_BL, Hand.Wing.Index_BT, 
           Mass_BL, Mass_BT, 
           Habitat_BT, Habitat_BL,
           Habitat.Density_BT, Habitat.Density_BL,
           Migration_BT, Migration_BL,
           Trophic.Level_BT, Trophic.Level_BL,
           Trophic.Niche_BT, Trophic.Niche_BL,
           Primary.Lifestyle_BT, Primary.Lifestyle_BL,
           Range.Size_BT, Range.Size_BL) %>% 
  mutate(HWI = coalesce(Hand.Wing.Index_BL, Hand.Wing.Index_BT),
         Mass = coalesce(Mass_BL, Mass_BT),
         Habitat = coalesce(Habitat_BT, Habitat_BL),
         Habitat.Density = coalesce(Habitat.Density_BT, Habitat.Density_BL),
         Migration = coalesce( Migration_BT, Migration_BL),
         Trophic.Level = coalesce(Trophic.Level_BT, Trophic.Level_BL),
         Trophic.Niche = coalesce(Trophic.Niche_BT, Trophic.Niche_BL),
         Primary.Lifestyle = coalesce(Primary.Lifestyle_BT, Primary.Lifestyle_BL),
         Range.Size = coalesce(Range.Size_BT, Range.Size_BL)) %>%
  select(sp_atlas, Accepted_SPNAME,
         HWI, Mass, Habitat, Habitat.Density, Migration, Trophic.Level, Trophic.Niche, Primary.Lifestyle, Range.Size)
colSums(is.na(AVONET_FINAL))

write.csv(AVONET_FINAL, "out/csv/Avonet_Matched_UTaxonstand.csv")
saveRDS(AVONET_FINAL, "out/rds/Avonet_Matched_UTaxonstand.csv")
```

## Niches df

```{r}
Niches <- readRDS("out/rds/Niches_df_v2.rds")
Niches_v <- Niches %>% pull(verbatim_name)

Niches_matched <- nameMatch(spList = Niches_v, author = F, spSource = databaseAves)

Niches_merged <- merge(Niches, Niches_matched %>% select(Submitted_Name, Accepted_SPNAME),
                       by.x = "verbatim_name", by.y="Submitted_Name")

colSums(is.na(Niches_merged))
```

## Merging all together

```{r}
AVONET_BL<- AVONET_FINAL %>% 
  left_join(BL_matched %>% 
              rename("BL_name" = "Submitted_Name") %>%
              select(BL_name, Accepted_SPNAME) %>% na.omit()) %>%
  left_join(BT_merged %>%
              rename("BT_name" = "sp_BirdTree") %>%
              select(BT_name, Accepted_SPNAME, "FP") %>% na.omit()) %>%
  left_join(Niches_merged %>%
              rename("Shapefile_name" = "verbatim_name") %>% filter(!is.na(Accepted_SPNAME)))


colSums(is.na(AVONET_BL))
write.csv(AVONET_BL, "out/csv/Avonet_FP_Matched_UTaxonstand.csv")


AVONET_BL %>% distinct(sp_atlas, sd_PC1) %>% na.omit() # 752 
```
